import { node as N } from "../node";
import type { SchemaNode, TxType } from "../../types";

/** Internal XML target schemas per transaction type. */
export const XML_TARGETS: Record<TxType, SchemaNode[]> = {
  "204": [
    N("tx01", "interchangeSenderID", "Sender ID", 0, "el"),
    N("tx02", "interchangeReceiverID", "Receiver ID", 0, "el"),
    N("tx03", "applicationSendersCode", "App Sender", 0, "el"),
    N("tx04", "applicationReceiversCode", "App Receiver", 0, "el"),
    N("tx05", "standardCarrierAlphaCode", "SCAC", 0, "el"),
    N("tx06", "shipmentIdentificationNumber", "Shipment ID", 0, "el"),
    N("tx07", "shipmentMethodOfPayment", "Payment Method", 0, "el"),
    N("tx08", "transactionSetPurposeCode", "Purpose Code", 0, "el"),
    N("tx09", "applicationType", "App Type", 0, "el"),
    N("txl1", "L11_list", "Header Refs", 0, "loop", { max: "99", kids: ["txl11", "txl12", "txl13"] }),
    N("txl11", "referenceIdentification", "Ref ID", 1, "el"),
    N("txl12", "referenceIdentificationQualifier", "Ref Qualifier", 1, "el"),
    N("txl13", "description", "Description", 1, "el"),
    N("txn1", "noteReferenceCode", "Note Code", 0, "el"),
    N("txn2", "freeFormMessage", "Note Text", 0, "el"),
    N("txe1", "equipmentNumber", "Equip #", 0, "el"),
    N("txe2", "equipmentDescriptionCode", "Equip Type", 0, "el"),
    N("txp1", "Loop0100/N1", "Parties", 0, "loop", {
      max: "5",
      kids: ["txp11", "txp12", "txp13", "txp14", "txp15", "txp16", "txp17", "txp18", "txp19"],
    }),
    N("txp11", "entityIdentifierCode", "Entity Code", 1, "el"),
    N("txp12", "name", "Name", 1, "el"),
    N("txp13", "identificationCodeQualifier", "ID Qual", 1, "el"),
    N("txp14", "identificationCode", "ID Code", 1, "el"),
    N("txp15", "addressInformation", "Address", 1, "el"),
    N("txp16", "cityName", "City", 1, "el"),
    N("txp17", "stateOrProvinceCode", "State", 1, "el"),
    N("txp18", "postalCode", "Zip", 1, "el"),
    N("txp19", "countryCode", "Country", 1, "el"),
    N("txs1", "Loop0300/S5", "Stops", 0, "loop", {
      max: "999",
      kids: [
        "txs11", "txs12", "txs13", "txs14", "txs15", "txs16", "txs17", "txs18",
        "txs19", "txs1a", "txs1b", "txs1c", "txs1d", "txs1e", "txs1f",
      ],
    }),
    N("txs11", "stopSequenceNumber", "Stop Seq", 1, "el"),
    N("txs12", "stopReasonCode", "Reason", 1, "el"),
    N("txs13", "Loop0310/L11/refId", "Stop Ref ID", 1, "el"),
    N("txs14", "Loop0310/L11/refQual", "Stop Ref Qual", 1, "el"),
    N("txs15", "G62/date", "Stop Date", 1, "el"),
    N("txs16", "G62/time", "Stop Time", 1, "el"),
    N("txs17", "AT8/weight", "Weight", 1, "el"),
    N("txs18", "AT8/weightQualifier", "Weight Qual", 1, "el"),
    N("txs19", "AT8/ladingQuantity", "Lading Qty", 1, "el"),
    N("txs1a", "N1/entityIdentifierCode", "Entity Code", 1, "el"),
    N("txs1b", "N1/name", "Party Name", 1, "el"),
    N("txs1c", "N3/addressInformation", "Address", 1, "el"),
    N("txs1d", "N4/cityName", "City", 1, "el"),
    N("txs1e", "N4/stateOrProvinceCode", "State", 1, "el"),
    N("txs1f", "N4/postalCode", "Zip", 1, "el"),
    N("txw1", "weight", "Total Weight", 0, "el"),
    N("txw2", "freightRate", "Freight Rate", 0, "el"),
    N("txw3", "totalCharges", "Total Charges", 0, "el"),
  ],
  "990": [
    N("t91", "standardCarrierAlphaCode", "SCAC", 0, "el"),
    N("t92", "shipmentIdentificationNumber", "Shipment ID", 0, "el"),
    N("t93", "date", "Date", 0, "el"),
    N("t94", "reservationActionCode", "Action Code", 0, "el"),
    N("t95", "N9/referenceIdentificationQualifier", "Ref Qual", 0, "el"),
    N("t96", "N9/referenceIdentification", "Ref ID", 0, "el"),
    N("t97", "K1/freeFormMessage", "Decline Reason", 0, "el"),
  ],
  "214": [
    N("t41", "B10/referenceIdentification", "Ref ID", 0, "el"),
    N("t42", "B10/shipmentIdentification", "Shipment ID", 0, "el"),
    N("t43", "B10/standardCarrierAlphaCode", "SCAC", 0, "el"),
    N("t44", "L11/referenceIdentification", "Ref ID", 0, "el"),
    N("t45", "L11/referenceIdentificationQualifier", "Ref Qual", 0, "el"),
    N("t46", "Loop0100/N1", "Parties", 0, "loop", {
      max: "3",
      kids: ["t461", "t462", "t463", "t464", "t465", "t466", "t467"],
    }),
    N("t461", "entityIdentifierCode", "Entity Code", 1, "el"),
    N("t462", "name", "Name", 1, "el"),
    N("t463", "addressInformation", "Address", 1, "el"),
    N("t464", "cityName", "City", 1, "el"),
    N("t465", "stateOrProvinceCode", "State", 1, "el"),
    N("t466", "postalCode", "Zip", 1, "el"),
    N("t467", "countryCode", "Country", 1, "el"),
    N("t47", "LX/assignedNumber", "Assigned #", 0, "el"),
    N("t48", "AT7/shipmentStatusCode", "Status Code", 0, "el"),
    N("t49", "AT7/statusReasonCode", "Reason Code", 0, "el"),
    N("t4a", "AT7/date", "Event Date", 0, "el"),
    N("t4b", "AT7/time", "Event Time", 0, "el"),
    N("t4c", "AT7/timeCode", "Time Zone", 0, "el"),
    N("t4d", "MS1/cityName", "Location City", 0, "el"),
    N("t4e", "MS1/stateOrProvinceCode", "Location State", 0, "el"),
    N("t4f", "MS2/equipmentNumber", "Equipment #", 0, "el"),
  ],
  "210": [
    N("t21", "B3/invoiceNumber", "Invoice #", 0, "el"),
    N("t22", "B3/shipmentIdentificationNumber", "Shipment ID", 0, "el"),
    N("t23", "B3/shipmentMethodOfPayment", "Payment", 0, "el"),
    N("t24", "B3/date", "Invoice Date", 0, "el"),
    N("t25", "B3/netAmountDue", "Amount Due", 0, "el"),
    N("t26", "B3/deliveryDate", "Delivery Date", 0, "el"),
    N("t27", "B3/standardCarrierAlphaCode", "SCAC", 0, "el"),
    N("t28", "B3/paymentDueDate", "Due Date", 0, "el"),
    N("t29", "C3/currencyCode", "Currency", 0, "el"),
    N("t2a", "N9 Loop", "Refs", 0, "loop", { max: "99", kids: ["t2a1", "t2a2"] }),
    N("t2a1", "referenceIdentificationQualifier", "Ref Qual", 1, "el"),
    N("t2a2", "referenceIdentification", "Ref ID", 1, "el"),
    N("t2b", "LX Loop", "Line Items", 0, "loop", {
      max: "999",
      kids: ["t2b1", "t2b2", "t2b3", "t2b4", "t2b5"],
    }),
    N("t2b1", "lineNumber", "Line #", 1, "el"),
    N("t2b2", "ladingDescription", "Description", 1, "el"),
    N("t2b3", "billedWeight", "Weight", 1, "el"),
    N("t2b4", "freightRate", "Rate", 1, "el"),
    N("t2b5", "charge", "Charge", 1, "el"),
    N("t2c", "L3/totalWeight", "Total Weight", 0, "el"),
    N("t2d", "L3/totalCharges", "Total Charges", 0, "el"),
  ],
  "850": [
    N("t81", "transactionSetPurposeCode", "Purpose", 0, "el"),
    N("t82", "purchaseOrderNumber", "PO #", 0, "el"),
    N("t83", "purchaseOrderDate", "PO Date", 0, "el"),
    N("t84", "N1 Loop", "Parties", 0, "loop", {
      max: "10",
      kids: ["t841", "t842", "t843", "t844", "t845", "t846"],
    }),
    N("t841", "entityIdentifierCode", "Entity Code", 1, "el"),
    N("t842", "name", "Name", 1, "el"),
    N("t843", "identificationCode", "GLN", 1, "el"),
    N("t844", "addressInformation", "Address", 1, "el"),
    N("t845", "cityName", "City", 1, "el"),
    N("t846", "postalCode", "Zip", 1, "el"),
    N("t85", "PO1 Loop", "Line Items", 0, "loop", {
      max: "999",
      kids: ["t851", "t852", "t853", "t854", "t855", "t856", "t857"],
    }),
    N("t851", "lineNumber", "Line #", 1, "el"),
    N("t852", "quantityOrdered", "Qty", 1, "el"),
    N("t853", "unitOfMeasure", "UOM", 1, "el"),
    N("t854", "unitPrice", "Price", 1, "el"),
    N("t855", "productId", "UPC", 1, "el"),
    N("t856", "buyerItemNumber", "Buyer SKU", 1, "el"),
    N("t857", "description", "Description", 1, "el"),
  ],
  "856": [
    N("t61", "BSN/shipmentIdentification", "Shipment ID", 0, "el"),
    N("t62", "BSN/shipmentDate", "Ship Date", 0, "el"),
    N("t63", "TD5/carrierSCAC", "SCAC", 0, "el"),
    N("t64", "TD3/trailerNumber", "Trailer #", 0, "el"),
    N("t65", "REF/bolNumber", "BOL #", 0, "el"),
    N("t66", "HL-O Loop", "Orders", 0, "loop", { max: "999", kids: ["t661", "t662"] }),
    N("t661", "PRF/poNumber", "PO #", 1, "el"),
    N("t662", "PRF/poDate", "PO Date", 1, "el"),
    N("t67", "HL-T Loop", "Pallets", 0, "loop", { max: "9999", kids: ["t671", "t672", "t673"] }),
    N("t671", "MAN/sscc18", "Pallet SSCC", 1, "el"),
    N("t672", "PO4/casesPerPallet", "Cases", 1, "el"),
    N("t673", "PO4/grossWeight", "Weight", 1, "el"),
    N("t68", "HL-I Loop", "Items", 0, "loop", {
      max: "9999",
      kids: ["t681", "t682", "t683", "t684", "t685", "t686"],
    }),
    N("t681", "LIN/upc", "UPC", 1, "el"),
    N("t682", "LIN/gtin", "GTIN", 1, "el"),
    N("t683", "SN1/qtyShipped", "Qty", 1, "el"),
    N("t684", "PID/description", "Desc", 1, "el"),
    N("t685", "MEA/weight", "Weight", 1, "el"),
    N("t686", "REF/lotNumber", "Lot #", 1, "el"),
  ],
  "855": [
    N("ta1", "ackType", "Ack Type", 0, "el"),
    N("ta2", "poNumber", "PO #", 0, "el"),
    N("ta3", "poDate", "PO Date", 0, "el"),
    N("ta4", "Line Loop", "Lines", 0, "loop", { max: "999", kids: ["ta41", "ta42", "ta43"] }),
    N("ta41", "lineNumber", "Line #", 1, "el"),
    N("ta42", "quantity", "Qty", 1, "el"),
    N("ta43", "lineStatus", "Status", 1, "el"),
  ],
  "810": [
    N("tb1", "invoiceDate", "Invoice Date", 0, "el"),
    N("tb2", "invoiceNumber", "Invoice #", 0, "el"),
    N("tb3", "poNumber", "PO #", 0, "el"),
    N("tb4", "IT1 Loop", "Lines", 0, "loop", {
      max: "999",
      kids: ["tb41", "tb42", "tb43", "tb44"],
    }),
    N("tb41", "lineNumber", "Line #", 1, "el"),
    N("tb42", "qtyInvoiced", "Qty", 1, "el"),
    N("tb43", "unitPrice", "Price", 1, "el"),
    N("tb44", "upc", "UPC", 1, "el"),
    N("tb5", "totalAmount", "Total", 0, "el"),
  ],
};
